package:
  name: locate
  version: "1.0.0"

source:
  path: .

build:
  script: {{ PYTHON }} setup.py install
  number: 0

requirements:
  build:
    - python=3.10.13
    - cython=3.0.6
    - htslib=1.21
  run:
    - python=3.10.13
    - scikit-learn=1.3.2
    - autogluon=1.0.0
    - samtools=1.21
    - minimap2=2.1.1
    - wtdbg=2.5

about:
  home: https://github.com/red-t/LOCATE
  license: MIT
  summary: "LOCATE (Long-read to Characterize All Transposable Elements) is a mapping-based method using long-read whole genome sequencing data to detect and assemble transposon insertions."